# Generated by Django 4.0 on 2022-01-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
